### YamlMime:ModuleUnit
uid: learn-m365-pr.bringing-all-together-engaging-virtual-events.produce-virtual-event
title: Produce your virtual event
metadata:
  unitType: learning-content
  title: Understand and optimize the attendee experience
  description: Learn how to produce a meeting or live event in Teams.
  ms.date: 07/20/2021
  author: lizap
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 7
content: |
  [!include[](includes/produce-virtual-event.md)] 