### YamlMime:ModuleUnit
uid: learn-m365.service-adoption-scale.training
title: Create awareness, training, and engagement models as part of the Scale phase
metadata:
  title: Create awareness, training, and engagement models as part of the Scale phase
  description: Learn how to create awareness, training, and engagement models as part of the Scale phase in the service adoption framework.
  ms.date: 10/01/2019
  author: lizap
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
  ROBOTS: NOINDEX
durationInMinutes: 7
content: |
  [!include[](includes/training.md)]